enableGlobalCache: false

plugins:
  - checksum: 68352ef664071c20f6f554e6d4c8ab9a78a40adcdc15208c9e1b8c891800709ebb8e38a0fbb4cc292d1c88d5eb8a5b3fd5baf01a884f4870ff877f58e0f878e9
    path: .yarn/plugins/@yarnpkg/plugin-tsconfig-workspaces.cjs
    spec: .yarn/standalone/tsconfig-workspaces/bundles/@yarnpkg/plugin-tsconfig-workspaces.js

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs
